version: "3"
services:
  api_service:
    platform: linux/amd64
    container_name: api_container
    image: vectornguyen76/flask_template_image
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.api.local
    ports:
      - 5001:5001
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db_service

  db_service:
    platform: linux/amd64
    container_name: db_container
    image: postgres:14.1
    env_file:
      - .env.db.local
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  nginx_service:
    platform: linux/amd64
    container_name: nginx_container
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - api_service
volumes:
  postgresql_data:
