[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "scikit-build",
  "cmake",
  "swig",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"

[project]
name = "spps"
version = "0.1.0"
description = "Spps computation core"

