name: Build choras and run test simulations

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # , "macos-latest", "windows-latest"
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'true'
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: choras
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
    - name: Setting up the environment
      shell: bash
      run:  pip install -r requirements.txt
        
