name: Build choras and run test simulations

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # , "macos-latest", "windows-latest"
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v5
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Setting up the environment
      shell: bash
      run:  |
            conda create -n choras python=3.10
            conda activate choras
            pip install -r requirements.txt
        
