name: test - Code Quality Check & Testing

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  code_quality_check:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install flake8==6.1.0 black==25.1.0 isort==5.12.0

      - name: Run Black (Code Formatting)
        run: black --check --config=".black" --exclude="(Diffusion|simulation-backend|edg-acoustic)" .

      # - name: Run isort (Import Sorting)
      #   run: isort --check-only --sp=".isort" --profile="black" .

      - name: Run Flake8 (Linting)
        run: flake8 .

  testing:
    needs: code_quality_check
    runs-on: windows-latest
    steps:
      - name: Checkout Code with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt simulation-backend/. Diffusion/. edg-acoustics/.

      - name: Run Tests
        run: flask tests
            